### ISSUE TITLE
Build Bill management view and controller

### ISSUE THREAD

**Issue by miguel-rivera** [miguel-rivera/Fission#11]
Using Spring MVC build a dynamic view as well as controller for the maintenance of  bill statements.
Following should be included before closing:

- [ ]  can add a new bill statement
- [ ]  can edit bill statements 
- [ ]  can save/load bill statements
- [ ]  can delete bill statements
